#!/bin/bash

set -euo pipefail

#######################################
# Update the Server Spack environment when its installation inputs change.
# Globals:
#   HOME
# Arguments:
#   1: Optional architecture already detected by shell startup.
# Outputs:
#   Writes update progress and installer output to stdout and stderr.
# Returns:
#   0 if the environment is current or installation succeeds, non-zero otherwise.
#######################################
function main() {
    local script_dir
    script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
    local architecture
    architecture="${1:-$("${HOME}/spack/bin/spack" -E arch)}"
    local stamp="${HOME}/spack/var/spack/environments/${architecture}/server/.configs-updated"

    # Include recipe directories to notice removals, but ignore generated bytecode.
    if [[ -f "${stamp}" ]]; then
        local changed_input
        changed_input="$(
            find "${script_dir}/spack.yaml" "${script_dir}/install/spack.sh" \
                "${script_dir}/update_spack.sh" "${script_dir}/spack_repo" \
                ! -path '*/__pycache__*' -newer "${stamp}" -print -quit
        )"
        [[ -n "${changed_input}" ]] || return 0
    fi

    bash "${script_dir}/install/spack.sh"

    # set -e stops here on installation failure, preserving the timestamp so startup retries.
    touch "${stamp}"
}

main "$@"
